version: "3.9"
services:
  frontend:
    image: node:17.3.0
    # build: ./frontend
    ports:
      - "3000:3000"
  backend:
    image: node:17.3.0
    # build: ./qlServer
    ports:
      - "3001:3001"
